### ISSUE TITLE
dali with libvips memory leak?

### ISSUE THREAD

**Issue by ttdonovan** [olxgroup-oss/dali#6]
After reading the blog post about "Presenting Dali, an Image Processor Service" we were inspired to try it with our own site. This specifically isn't an issue with Dali but wondering if you see similar memory behaviors running it in production. Mostly this service is used to resize a PNG to smaller JPEG for customer front-end.

container: ~300 request per min
scale-up: average cpu over 60%
scale-down: average cpu under 20%

<img width="1106" alt="memory" src="https://user-images.githubusercontent.com/10460/81214140-3f650580-8f8c-11ea-8eb0-9dbd1f85bdb4.png">

Thanks!

**Comment by augustocdias** [comment]
Hey,
We see this happening from time to time but we weren’t able to find the root cause yet. 
I personally suspect it’s a deadlock and not a leak. The memory grows due to requests being piled up. Again, it’s just my gut feeling. We couldn’t track the root cause yet.

**Comment by ttdonovan** [comment]
We've made this simple change to the `Dockerfile.base` and are having better luck so far. I did see in the changelog of libvips 9.8.2 this comment `fix a deadlock with --vips-leak [DarthSim]`. I'll follow up with a memory graph later once it's been running for few hours.

```
diff --git a/Dockerfile.base b/Dockerfile.base
index 87ad2bd..5791982 100644
--- a/Dockerfile.base
+++ b/Dockerfile.base
@@ -2,9 +2,9 @@
 
 FROM rust:1.42-alpine3.11
 
-ENV VIPS_VERSION=8.9.1
+ENV VIPS_VERSION=8.9.2
 
-RUN apk add --update --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community \
+apk add --update --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main \
             build-base \
             pkgconfig \
             openssl-dev\
@@ -21,7 +21,7 @@ RUN apk add --update --no-cache --repository=http://dl-cdn.alpinelinux.org/alpin
             orc-dev \
             libwebp-dev \
             libheif-dev \
-            libimagequant-dev 
+            libimagequant-dev
 
 RUN wget https://github.com/libvips/libvips/releases/download/v${VIPS_VERSION}/vips-${VIPS_VERSION}.tar.gz
```

**Comment by augustocdias** [comment]
This is great news. Could you make a pull request?

**Comment by augustocdias** [comment]
Just a heads up
We were hit by an issue today with libheif which was causing the application to crash.
The root cause was this issue in libheif:
https://github.com/strukturag/libheif/issues/132
I suggest you update your images. I've pushed new `Dockerfiles` with the fix already

**Comment by ttdonovan** [comment]
OK thanks for the update, I don't think we're using any heif. Performance has been stable since the update to libvips. I think with the latest commits to `master` this issue can be marked as resolved and closed.

**Comment by augustocdias** [comment]
I’ll close then. Thank you very much
